#!/bin/bash
#Script Name: ATM
#This script only holds up to 9999 bank accounts

userLogin() {
  read -p "Enter your accountNumber: " inputAcctNum
  actualAcctNum=$(cut -d":" -f3 accountsFile | grep inputAcctNum)
  while [[ $actualAcctNum = "" ]]
  do
    read -p "Please enter a valid accountNumber: " inputAcctNum
  done

  actualAcctPin=$(grep 4144 accountsFile | cut -d":" -f1)
  read -p "Enter your pin: " inputAcctPin
  while[[ $inputAcctPin ]]
  do
    read -p "Enter your pin: " inputAcctPin
  done
}

makeNewUser() {
  if [ ! -d ./transactionHistories ] ; then
    mkdir transactionHistories
  fi

  userPin=0

  read -p "Enter your first name: " firstName
  read -p "Enter your last name: " lastName
  fullName="$firstName""_""$lastName"

  read -p "Enter your initial deposit ammount: " depositAmt
  while [[ $userPin -lt 1000 || $userPin -gt 9999 ]]
  do
    echo  "Enter the 4 digit pin you will like to use"
    read userPin </dev/tty
  done

  userAcctNum=$(shuf -i 1000-9999 -n 1)

  echo "Your account number is: $userAcctNum please remember it!"
  echo "$userPin:$fullName:$userAcctNum:$depositAmt" >> accountsFile

  userTransactions="$userAcctNum:$fullName"
  #echo $userTransactions
  touch transactionHistories/$userTransactions
  echo "balance: $depositAmt" >> $userTransactions
  echo "+$depositAmt" >> $userTransactions

}


welcomeScreen() {
  echo which would you like to do?
  echo New User
  echo Existing User
  read -p ":" userAns

  echo $userAns

  case $userAns in
    "New User")
      makeNewUser ;;
    "Existing User")
      userLogin ;;
  esac
}
